name: Build and Deploy MERN â†’ EC2

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # ---------- FRONTEND ----------
      - name: Install frontend deps
        run: |
          cd frontend
          npm ci
      
      - name: Build frontend
        run: |
          cd frontend
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build
      
      - name: Archive build
        run: tar -C frontend/build -czf build.tar.gz .

      - name: Upload frontend to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          overwrite: true
          source: "build.tar.gz"
          target: "/tmp/build.tar.gz"


      # ---------- BACKEND ----------
      - name: Upload backend code to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          overwrite: true
          source: "./server.js,./app.js,./package.json,./package-lock.json,./.variables.env,./routes,./controllers,./models,./handlers,./public,./data,./setup"
          target: "/var/www/backend"


      # ---------- DEPLOY ----------
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            APP_DIR=/var/www/myapp
            BACK_DIR=/var/www/backend

            # FRONTEND
            sudo mkdir -p $APP_DIR/build
            sudo rm -rf $APP_DIR/build/*
            sudo tar -xzf /tmp/build.tar.gz -C $APP_DIR/build
            sudo rm /tmp/build.tar.gz

            # BACKEND
            cd $BACK_DIR
            npm install --production

            # PM2 start / restart
            pm2 restart backend || pm2 start server.js --name backend

            sudo nginx -t
            sudo systemctl reload nginx
